#
# Module manifest for module 'HPEOneView.700'
#
# Generated by: Hewlett-Packard Enterprise
#
# Generated on: 8/9/2022
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'HPEOneView.700.psm1'

# Version number of this module.
ModuleVersion = '7.00.3307.2893'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '1c1507cc-089e-412f-b686-7ba9c24c2330'

# Author of this module
Author = 'Hewlett-Packard Enterprise'

# Company or vendor of this module
CompanyName = 'Hewlett-Packard Enterprise'

# Copyright statement for this module
Copyright = '    (C) Copyright 2013-2022 Hewlett Packard Enterprise Development LP

    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to deal
    in the Software without restriction, including without limitation the rights
    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in
    all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
    THE SOFTWARE.'

# Description of the functionality provided by this module
Description = 'HPE OneView PowerShell Library'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
ClrVersion = '4.0.30319.42000'

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = 'lib\HPEOneView_Classes.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = 'Appliance.format.ps1xml', 'Cluster.format.ps1xml',
               'Networking.format.ps1xml', 'Server.format.ps1xml',
               'Storage.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
# FunctionsToExport = '*'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
# CmdletsToExport = '*'

# Variables to export from this module
# VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
# AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = 'HPEOneView.700.psd1',
            'HPEOneView.700.psm1',
            'Appliance.format.ps1xml',
            'Cluster.format.ps1xml',
            'Networking.format.ps1xml',
            'Server.format.ps1xml',
            'Storage.format.ps1xml',
            'HPEOneView.700_1c1507cc-089e-412f-b686-7ba9c24c2330_HelpInfo.xml',
            'HPEOneView.700_1c1507cc-089e-412f-b686-7ba9c24c2330_ModuleInfo.xml',
            'en-US\about_Appliance_Connections.help.txt',
            'en-US\about_Appliance_Connection_Permissions.help.txt',
            'en-US\about_Two_Factor_Authentication.help.txt',
            'en-US\about_HPEOneView.700.help.txt',
            'en-US\HPEOneView.700.psm1-help.xml',
            'lib\HPEOneView_Classes.dll',
            'Samples\AddServers_Monitored_Sample.ps1',
            'Samples\AddStorageSystem_Sample.ps1',
            'Samples\Alerts_Sample.ps1',
            'Samples\Appliance_Backup_Sample.ps1',
            'Samples\ApplianceConfig_Sample.ps1',
            'Samples\ComposerApplianceConfig_Sample.ps1',
            'Samples\Configure_IIS_WebDav_ExternalRepo_Sample.ps1',
            'Samples\ConfigureRemoteSupport_Sample.ps1',
            'Samples\CreateEnclosureGroup_Sample.ps1',
            'Samples\DefineLogicalInterconnectGroup_AA_VC_Sample.ps1',
            'Samples\DefineLogicalInterconnectGroup_Sample.ps1',
            'Samples\DefineNetworks_AA_VC_Sample.ps1',
            'Samples\DefineNetworks_Sample.ps1',
            'Samples\Server_Multiconnection_AA_VC_Sample.ps1',
            'Samples\Server_Multiconnection_Sample.ps1',
            'Samples\Server_Multiconnection_SAN_Storage_Sample.ps1',
            'Samples\Server_Profile_Template_Multiconnection_Sample.ps1',
            'Samples\Server_Profile_Template_Rack_Server_Sample.ps1',
            'Samples\Wipe_Appliance.ps1'
# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Hewlett', 'Packard', 'Enterprise', 'HPE', 'HPOneView', 'HPEOneView',
               'HPESynergy'

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/HewlettPackard/POSH-HPEOneView/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'http://hewlettpackard.github.io/POSH-HPEOneView'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = "Release 7.00.3307.2894

- Initial HPE OneView 7.00 library release.
- All HPE BladeSystem c-Class features have been removed from the library. This aligns with the removed features in HPE OneView 7.00 for c-Class resources.
- Added back BNA support after mistakenly removing.
- Fixed Get-OVNetwork returning all index resources when -Type FC parameter was provided.
- Added password property redaction method to hide passwords when using -Verbose output.
- Fixed PowerShell platform detection when attempting to identify .Net client installed.
- [#614] Addressed issue with iLO self-signed certificate handling within PowerShell Core.
- Changes to New-OVServerProfileLogicalDiskController and the -ControllerID parameter now has a new enum list that doesn't allow spaces in the parameter value. Prior, 'Mezz 1' was an allowed value, it must now be 'Mezz1'.
- Updated New-OVServerProfileLogicalDiskController by adding spare drive policy parameter to manage spare drive policy with HPE Synergy D3940 and Gen10 or newer controllers.
- Updated New-OVServerProfileLogicalDisk by adding add spare drive parameter to manage spare drive policy with HPE Synergy D3940 and Gen10 or newer controllers.
- Removed StoreVirtual support due to the removal of support from HPE OneView 7.0.
- Added Cmdlets to help manage appliance static routes.  Only supported with virtual machine appliance, and not HPE Synergy Composer."

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
HelpInfoURI = 'http://hewlettpackard.github.io/POSH-HPEOneView/UpdateHelp'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


