version: 9.10.{build}
branches:
  only:
  - 9.10
skip_tags: true
skip_commits:
  files:
    - LICENSE
    - '*.psd1'
    - '**/*.xml'
    - '**/*.txt'
    - '*.md'
    - '**/*.md'
    - '*.yml'
    - '**/*.yml'

build_cloud: doc-hyp-cluster1
image: win10-ent-worker
clone_folder: C:\Projects\HPEOneView.910
init:
- pwsh: >-
    Write-Host "STARTING"

    $env:PSModulePath += ";C:\Projects"

environment:
  ACCESS_TOKEN:
    secure: 2cM8izTtmmL7B0li5CCq5Qa63Yu9+VyIN2SHlNSOpEOSwKj0wpqb4aopMf4Fyu7X
build: off
test_script:
- pwsh: >-
    Write-Host "Testing. No tests will be performed."
    Write-Host ("Slug: {0}" -f ${env:APPVEYOR_PROJECT_SLUG})
    Write-Host ("Version: {0}" -f ${env:APPVEYOR_BUILD_VERSION})

on_finish:
  - ps: $pause = $true; iex ((new-object net.webclient).DownloadString('https://gist.githubusercontent.com/ChrisLynchHPE/d572a8fd60d01f2f3c5c3d0aa882f833/raw/3c51c4155cba1e64cffac60b2893fae0c00f38f3/pause.ps1'))
notifications: off
